// automatically generated by the FlatBuffers compiler, do not modify

#ifndef FLATBUFFERS_GENERATED_GETMSGREQ_FBS_MSG_H_
#define FLATBUFFERS_GENERATED_GETMSGREQ_FBS_MSG_H_

#include "flatbuffers/flatbuffers.h"

namespace fbs {
struct Session;
struct GeneralResponse;
}  // namespace fbs

namespace fbs {
namespace msg {

struct GetMsgRequest;

struct GetMsgRequest FLATBUFFERS_FINAL_CLASS : private flatbuffers::Table {
  const fbs::Session *session() const { return GetPointer<const fbs::Session *>(4); }
  const flatbuffers::String *channel() const { return GetPointer<const flatbuffers::String *>(6); }
  bool Verify(flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<flatbuffers::uoffset_t>(verifier, 4 /* session */) &&
           verifier.VerifyTable(session()) &&
           VerifyField<flatbuffers::uoffset_t>(verifier, 6 /* channel */) &&
           verifier.Verify(channel()) &&
           verifier.EndTable();
  }
};

struct GetMsgRequestBuilder {
  flatbuffers::FlatBufferBuilder &fbb_;
  flatbuffers::uoffset_t start_;
  void add_session(flatbuffers::Offset<fbs::Session> session) { fbb_.AddOffset(4, session); }
  void add_channel(flatbuffers::Offset<flatbuffers::String> channel) { fbb_.AddOffset(6, channel); }
  GetMsgRequestBuilder(flatbuffers::FlatBufferBuilder &_fbb) : fbb_(_fbb) { start_ = fbb_.StartTable(); }
  GetMsgRequestBuilder &operator=(const GetMsgRequestBuilder &);
  flatbuffers::Offset<GetMsgRequest> Finish() {
    auto o = flatbuffers::Offset<GetMsgRequest>(fbb_.EndTable(start_, 2));
    return o;
  }
};

inline flatbuffers::Offset<GetMsgRequest> CreateGetMsgRequest(flatbuffers::FlatBufferBuilder &_fbb,
   flatbuffers::Offset<fbs::Session> session = 0,
   flatbuffers::Offset<flatbuffers::String> channel = 0) {
  GetMsgRequestBuilder builder_(_fbb);
  builder_.add_channel(channel);
  builder_.add_session(session);
  return builder_.Finish();
}

inline const fbs::msg::GetMsgRequest *GetGetMsgRequest(const void *buf) { return flatbuffers::GetRoot<fbs::msg::GetMsgRequest>(buf); }

inline bool VerifyGetMsgRequestBuffer(flatbuffers::Verifier &verifier) { return verifier.VerifyBuffer<fbs::msg::GetMsgRequest>(); }

inline void FinishGetMsgRequestBuffer(flatbuffers::FlatBufferBuilder &fbb, flatbuffers::Offset<fbs::msg::GetMsgRequest> root) { fbb.Finish(root); }

}  // namespace msg
}  // namespace fbs

#endif  // FLATBUFFERS_GENERATED_GETMSGREQ_FBS_MSG_H_
