// automatically generated by the FlatBuffers compiler, do not modify

#ifndef FLATBUFFERS_GENERATED_EDITPOSTREQ_FBS_POST_H_
#define FLATBUFFERS_GENERATED_EDITPOSTREQ_FBS_POST_H_

#include "flatbuffers/flatbuffers.h"

namespace fbs {
struct Session;
struct GeneralResponse;
}  // namespace fbs

namespace fbs {
namespace post {

struct EditPostRequest;

struct EditPostRequest FLATBUFFERS_FINAL_CLASS : private flatbuffers::Table {
  const fbs::Session *session() const { return GetPointer<const fbs::Session *>(4); }
  uint64_t post_id() const { return GetField<uint64_t>(6, 0); }
  const flatbuffers::String *content() const { return GetPointer<const flatbuffers::String *>(8); }
  bool Verify(flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<flatbuffers::uoffset_t>(verifier, 4 /* session */) &&
           verifier.VerifyTable(session()) &&
           VerifyField<uint64_t>(verifier, 6 /* post_id */) &&
           VerifyField<flatbuffers::uoffset_t>(verifier, 8 /* content */) &&
           verifier.Verify(content()) &&
           verifier.EndTable();
  }
};

struct EditPostRequestBuilder {
  flatbuffers::FlatBufferBuilder &fbb_;
  flatbuffers::uoffset_t start_;
  void add_session(flatbuffers::Offset<fbs::Session> session) { fbb_.AddOffset(4, session); }
  void add_post_id(uint64_t post_id) { fbb_.AddElement<uint64_t>(6, post_id, 0); }
  void add_content(flatbuffers::Offset<flatbuffers::String> content) { fbb_.AddOffset(8, content); }
  EditPostRequestBuilder(flatbuffers::FlatBufferBuilder &_fbb) : fbb_(_fbb) { start_ = fbb_.StartTable(); }
  EditPostRequestBuilder &operator=(const EditPostRequestBuilder &);
  flatbuffers::Offset<EditPostRequest> Finish() {
    auto o = flatbuffers::Offset<EditPostRequest>(fbb_.EndTable(start_, 3));
    return o;
  }
};

inline flatbuffers::Offset<EditPostRequest> CreateEditPostRequest(flatbuffers::FlatBufferBuilder &_fbb,
   flatbuffers::Offset<fbs::Session> session = 0,
   uint64_t post_id = 0,
   flatbuffers::Offset<flatbuffers::String> content = 0) {
  EditPostRequestBuilder builder_(_fbb);
  builder_.add_post_id(post_id);
  builder_.add_content(content);
  builder_.add_session(session);
  return builder_.Finish();
}

inline const fbs::post::EditPostRequest *GetEditPostRequest(const void *buf) { return flatbuffers::GetRoot<fbs::post::EditPostRequest>(buf); }

inline bool VerifyEditPostRequestBuffer(flatbuffers::Verifier &verifier) { return verifier.VerifyBuffer<fbs::post::EditPostRequest>(); }

inline void FinishEditPostRequestBuffer(flatbuffers::FlatBufferBuilder &fbb, flatbuffers::Offset<fbs::post::EditPostRequest> root) { fbb.Finish(root); }

}  // namespace post
}  // namespace fbs

#endif  // FLATBUFFERS_GENERATED_EDITPOSTREQ_FBS_POST_H_
