// automatically generated by the FlatBuffers compiler, do not modify

#ifndef FLATBUFFERS_GENERATED_GETCOMMENTREQ_FBS_POST_H_
#define FLATBUFFERS_GENERATED_GETCOMMENTREQ_FBS_POST_H_

#include "flatbuffers/flatbuffers.h"

namespace fbs {
struct Session;
struct GeneralResponse;
}  // namespace fbs

namespace fbs {
namespace post {

struct GetCommentRequest;

struct GetCommentRequest FLATBUFFERS_FINAL_CLASS : private flatbuffers::Table {
  const fbs::Session *session() const { return GetPointer<const fbs::Session *>(4); }
  uint64_t post_id() const { return GetField<uint64_t>(6, 0); }
  uint64_t comment_id() const { return GetField<uint64_t>(8, 0); }
  bool Verify(flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<flatbuffers::uoffset_t>(verifier, 4 /* session */) &&
           verifier.VerifyTable(session()) &&
           VerifyField<uint64_t>(verifier, 6 /* post_id */) &&
           VerifyField<uint64_t>(verifier, 8 /* comment_id */) &&
           verifier.EndTable();
  }
};

struct GetCommentRequestBuilder {
  flatbuffers::FlatBufferBuilder &fbb_;
  flatbuffers::uoffset_t start_;
  void add_session(flatbuffers::Offset<fbs::Session> session) { fbb_.AddOffset(4, session); }
  void add_post_id(uint64_t post_id) { fbb_.AddElement<uint64_t>(6, post_id, 0); }
  void add_comment_id(uint64_t comment_id) { fbb_.AddElement<uint64_t>(8, comment_id, 0); }
  GetCommentRequestBuilder(flatbuffers::FlatBufferBuilder &_fbb) : fbb_(_fbb) { start_ = fbb_.StartTable(); }
  GetCommentRequestBuilder &operator=(const GetCommentRequestBuilder &);
  flatbuffers::Offset<GetCommentRequest> Finish() {
    auto o = flatbuffers::Offset<GetCommentRequest>(fbb_.EndTable(start_, 3));
    return o;
  }
};

inline flatbuffers::Offset<GetCommentRequest> CreateGetCommentRequest(flatbuffers::FlatBufferBuilder &_fbb,
   flatbuffers::Offset<fbs::Session> session = 0,
   uint64_t post_id = 0,
   uint64_t comment_id = 0) {
  GetCommentRequestBuilder builder_(_fbb);
  builder_.add_comment_id(comment_id);
  builder_.add_post_id(post_id);
  builder_.add_session(session);
  return builder_.Finish();
}

inline const fbs::post::GetCommentRequest *GetGetCommentRequest(const void *buf) { return flatbuffers::GetRoot<fbs::post::GetCommentRequest>(buf); }

inline bool VerifyGetCommentRequestBuffer(flatbuffers::Verifier &verifier) { return verifier.VerifyBuffer<fbs::post::GetCommentRequest>(); }

inline void FinishGetCommentRequestBuffer(flatbuffers::FlatBufferBuilder &fbb, flatbuffers::Offset<fbs::post::GetCommentRequest> root) { fbb.Finish(root); }

}  // namespace post
}  // namespace fbs

#endif  // FLATBUFFERS_GENERATED_GETCOMMENTREQ_FBS_POST_H_
