// automatically generated by the FlatBuffers compiler, do not modify

#ifndef FLATBUFFERS_GENERATED_LIKEREQ_FBS_POST_H_
#define FLATBUFFERS_GENERATED_LIKEREQ_FBS_POST_H_

#include "flatbuffers/flatbuffers.h"

namespace fbs {
struct Session;
struct GeneralResponse;
}  // namespace fbs

namespace fbs {
namespace post {

struct LikeRequest;

struct LikeRequest FLATBUFFERS_FINAL_CLASS : private flatbuffers::Table {
  const fbs::Session *session() const { return GetPointer<const fbs::Session *>(4); }
  uint64_t post_id() const { return GetField<uint64_t>(6, 0); }
  int32_t like_num() const { return GetField<int32_t>(8, 0); }
  bool Verify(flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<flatbuffers::uoffset_t>(verifier, 4 /* session */) &&
           verifier.VerifyTable(session()) &&
           VerifyField<uint64_t>(verifier, 6 /* post_id */) &&
           VerifyField<int32_t>(verifier, 8 /* like_num */) &&
           verifier.EndTable();
  }
};

struct LikeRequestBuilder {
  flatbuffers::FlatBufferBuilder &fbb_;
  flatbuffers::uoffset_t start_;
  void add_session(flatbuffers::Offset<fbs::Session> session) { fbb_.AddOffset(4, session); }
  void add_post_id(uint64_t post_id) { fbb_.AddElement<uint64_t>(6, post_id, 0); }
  void add_like_num(int32_t like_num) { fbb_.AddElement<int32_t>(8, like_num, 0); }
  LikeRequestBuilder(flatbuffers::FlatBufferBuilder &_fbb) : fbb_(_fbb) { start_ = fbb_.StartTable(); }
  LikeRequestBuilder &operator=(const LikeRequestBuilder &);
  flatbuffers::Offset<LikeRequest> Finish() {
    auto o = flatbuffers::Offset<LikeRequest>(fbb_.EndTable(start_, 3));
    return o;
  }
};

inline flatbuffers::Offset<LikeRequest> CreateLikeRequest(flatbuffers::FlatBufferBuilder &_fbb,
   flatbuffers::Offset<fbs::Session> session = 0,
   uint64_t post_id = 0,
   int32_t like_num = 0) {
  LikeRequestBuilder builder_(_fbb);
  builder_.add_post_id(post_id);
  builder_.add_like_num(like_num);
  builder_.add_session(session);
  return builder_.Finish();
}

inline const fbs::post::LikeRequest *GetLikeRequest(const void *buf) { return flatbuffers::GetRoot<fbs::post::LikeRequest>(buf); }

inline bool VerifyLikeRequestBuffer(flatbuffers::Verifier &verifier) { return verifier.VerifyBuffer<fbs::post::LikeRequest>(); }

inline void FinishLikeRequestBuffer(flatbuffers::FlatBufferBuilder &fbb, flatbuffers::Offset<fbs::post::LikeRequest> root) { fbb.Finish(root); }

}  // namespace post
}  // namespace fbs

#endif  // FLATBUFFERS_GENERATED_LIKEREQ_FBS_POST_H_
