// automatically generated by the FlatBuffers compiler, do not modify

#ifndef FLATBUFFERS_GENERATED_ADDFRIENDREQ_FBS_ACCOUNT_H_
#define FLATBUFFERS_GENERATED_ADDFRIENDREQ_FBS_ACCOUNT_H_

#include "flatbuffers/flatbuffers.h"

namespace fbs {
struct Session;
struct GeneralResponse;
}  // namespace fbs

namespace fbs {
namespace account {

struct AddFriendRequest;

struct AddFriendRequest FLATBUFFERS_FINAL_CLASS : private flatbuffers::Table {
  const fbs::Session *session() const { return GetPointer<const fbs::Session *>(4); }
  const flatbuffers::String *username() const { return GetPointer<const flatbuffers::String *>(6); }
  bool Verify(flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<flatbuffers::uoffset_t>(verifier, 4 /* session */) &&
           verifier.VerifyTable(session()) &&
           VerifyField<flatbuffers::uoffset_t>(verifier, 6 /* username */) &&
           verifier.Verify(username()) &&
           verifier.EndTable();
  }
};

struct AddFriendRequestBuilder {
  flatbuffers::FlatBufferBuilder &fbb_;
  flatbuffers::uoffset_t start_;
  void add_session(flatbuffers::Offset<fbs::Session> session) { fbb_.AddOffset(4, session); }
  void add_username(flatbuffers::Offset<flatbuffers::String> username) { fbb_.AddOffset(6, username); }
  AddFriendRequestBuilder(flatbuffers::FlatBufferBuilder &_fbb) : fbb_(_fbb) { start_ = fbb_.StartTable(); }
  AddFriendRequestBuilder &operator=(const AddFriendRequestBuilder &);
  flatbuffers::Offset<AddFriendRequest> Finish() {
    auto o = flatbuffers::Offset<AddFriendRequest>(fbb_.EndTable(start_, 2));
    return o;
  }
};

inline flatbuffers::Offset<AddFriendRequest> CreateAddFriendRequest(flatbuffers::FlatBufferBuilder &_fbb,
   flatbuffers::Offset<fbs::Session> session = 0,
   flatbuffers::Offset<flatbuffers::String> username = 0) {
  AddFriendRequestBuilder builder_(_fbb);
  builder_.add_username(username);
  builder_.add_session(session);
  return builder_.Finish();
}

inline const fbs::account::AddFriendRequest *GetAddFriendRequest(const void *buf) { return flatbuffers::GetRoot<fbs::account::AddFriendRequest>(buf); }

inline bool VerifyAddFriendRequestBuffer(flatbuffers::Verifier &verifier) { return verifier.VerifyBuffer<fbs::account::AddFriendRequest>(); }

inline void FinishAddFriendRequestBuffer(flatbuffers::FlatBufferBuilder &fbb, flatbuffers::Offset<fbs::account::AddFriendRequest> root) { fbb.Finish(root); }

}  // namespace account
}  // namespace fbs

#endif  // FLATBUFFERS_GENERATED_ADDFRIENDREQ_FBS_ACCOUNT_H_
