// automatically generated by the FlatBuffers compiler, do not modify

#ifndef FLATBUFFERS_GENERATED_EDITPROFILEREQ_FBS_ACCOUNT_H_
#define FLATBUFFERS_GENERATED_EDITPROFILEREQ_FBS_ACCOUNT_H_

#include "flatbuffers/flatbuffers.h"

namespace fbs {
struct Session;
struct GeneralResponse;
}  // namespace fbs

namespace fbs {
namespace account {

struct BirthdayStruct;
struct EditProfileRequest;

MANUALLY_ALIGNED_STRUCT(4) BirthdayStruct FLATBUFFERS_FINAL_CLASS {
 private:
  uint32_t year_;
  uint32_t month_;
  uint32_t day_;

 public:
  BirthdayStruct(uint32_t year, uint32_t month, uint32_t day)
    : year_(flatbuffers::EndianScalar(year)), month_(flatbuffers::EndianScalar(month)), day_(flatbuffers::EndianScalar(day)) { }

  uint32_t year() const { return flatbuffers::EndianScalar(year_); }
  uint32_t month() const { return flatbuffers::EndianScalar(month_); }
  uint32_t day() const { return flatbuffers::EndianScalar(day_); }
};
STRUCT_END(BirthdayStruct, 12);

struct EditProfileRequest FLATBUFFERS_FINAL_CLASS : private flatbuffers::Table {
  const fbs::Session *session() const { return GetPointer<const fbs::Session *>(4); }
  uint8_t edit_nickname() const { return GetField<uint8_t>(6, 0); }
  const flatbuffers::String *nickname() const { return GetPointer<const flatbuffers::String *>(8); }
  uint8_t edit_birthday() const { return GetField<uint8_t>(10, 0); }
  const BirthdayStruct *birthday() const { return GetStruct<const BirthdayStruct *>(12); }
  bool Verify(flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<flatbuffers::uoffset_t>(verifier, 4 /* session */) &&
           verifier.VerifyTable(session()) &&
           VerifyField<uint8_t>(verifier, 6 /* edit_nickname */) &&
           VerifyField<flatbuffers::uoffset_t>(verifier, 8 /* nickname */) &&
           verifier.Verify(nickname()) &&
           VerifyField<uint8_t>(verifier, 10 /* edit_birthday */) &&
           VerifyField<BirthdayStruct>(verifier, 12 /* birthday */) &&
           verifier.EndTable();
  }
};

struct EditProfileRequestBuilder {
  flatbuffers::FlatBufferBuilder &fbb_;
  flatbuffers::uoffset_t start_;
  void add_session(flatbuffers::Offset<fbs::Session> session) { fbb_.AddOffset(4, session); }
  void add_edit_nickname(uint8_t edit_nickname) { fbb_.AddElement<uint8_t>(6, edit_nickname, 0); }
  void add_nickname(flatbuffers::Offset<flatbuffers::String> nickname) { fbb_.AddOffset(8, nickname); }
  void add_edit_birthday(uint8_t edit_birthday) { fbb_.AddElement<uint8_t>(10, edit_birthday, 0); }
  void add_birthday(const BirthdayStruct *birthday) { fbb_.AddStruct(12, birthday); }
  EditProfileRequestBuilder(flatbuffers::FlatBufferBuilder &_fbb) : fbb_(_fbb) { start_ = fbb_.StartTable(); }
  EditProfileRequestBuilder &operator=(const EditProfileRequestBuilder &);
  flatbuffers::Offset<EditProfileRequest> Finish() {
    auto o = flatbuffers::Offset<EditProfileRequest>(fbb_.EndTable(start_, 5));
    return o;
  }
};

inline flatbuffers::Offset<EditProfileRequest> CreateEditProfileRequest(flatbuffers::FlatBufferBuilder &_fbb,
   flatbuffers::Offset<fbs::Session> session = 0,
   uint8_t edit_nickname = 0,
   flatbuffers::Offset<flatbuffers::String> nickname = 0,
   uint8_t edit_birthday = 0,
   const BirthdayStruct *birthday = 0) {
  EditProfileRequestBuilder builder_(_fbb);
  builder_.add_birthday(birthday);
  builder_.add_nickname(nickname);
  builder_.add_session(session);
  builder_.add_edit_birthday(edit_birthday);
  builder_.add_edit_nickname(edit_nickname);
  return builder_.Finish();
}

inline const fbs::account::EditProfileRequest *GetEditProfileRequest(const void *buf) { return flatbuffers::GetRoot<fbs::account::EditProfileRequest>(buf); }

inline bool VerifyEditProfileRequestBuffer(flatbuffers::Verifier &verifier) { return verifier.VerifyBuffer<fbs::account::EditProfileRequest>(); }

inline void FinishEditProfileRequestBuffer(flatbuffers::FlatBufferBuilder &fbb, flatbuffers::Offset<fbs::account::EditProfileRequest> root) { fbb.Finish(root); }

}  // namespace account
}  // namespace fbs

#endif  // FLATBUFFERS_GENERATED_EDITPROFILEREQ_FBS_ACCOUNT_H_
