// automatically generated by the FlatBuffers compiler, do not modify

#ifndef FLATBUFFERS_GENERATED_GETPROFILERESP_FBS_ACCOUNT_H_
#define FLATBUFFERS_GENERATED_GETPROFILERESP_FBS_ACCOUNT_H_

#include "flatbuffers/flatbuffers.h"

namespace fbs {
struct Session;
struct GeneralResponse;
}  // namespace fbs

namespace fbs {
namespace account {

struct GetProfileResponse;

struct GetProfileResponse FLATBUFFERS_FINAL_CLASS : private flatbuffers::Table {
  fbs::Status status_code() const { return static_cast<fbs::Status>(GetField<int8_t>(4, 0)); }
  const fbs::Session *session() const { return GetPointer<const fbs::Session *>(6); }
  const flatbuffers::String *nickname() const { return GetPointer<const flatbuffers::String *>(8); }
  const flatbuffers::String *birthday() const { return GetPointer<const flatbuffers::String *>(10); }
  bool Verify(flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<int8_t>(verifier, 4 /* status_code */) &&
           VerifyField<flatbuffers::uoffset_t>(verifier, 6 /* session */) &&
           verifier.VerifyTable(session()) &&
           VerifyField<flatbuffers::uoffset_t>(verifier, 8 /* nickname */) &&
           verifier.Verify(nickname()) &&
           VerifyField<flatbuffers::uoffset_t>(verifier, 10 /* birthday */) &&
           verifier.Verify(birthday()) &&
           verifier.EndTable();
  }
};

struct GetProfileResponseBuilder {
  flatbuffers::FlatBufferBuilder &fbb_;
  flatbuffers::uoffset_t start_;
  void add_status_code(fbs::Status status_code) { fbb_.AddElement<int8_t>(4, static_cast<int8_t>(status_code), 0); }
  void add_session(flatbuffers::Offset<fbs::Session> session) { fbb_.AddOffset(6, session); }
  void add_nickname(flatbuffers::Offset<flatbuffers::String> nickname) { fbb_.AddOffset(8, nickname); }
  void add_birthday(flatbuffers::Offset<flatbuffers::String> birthday) { fbb_.AddOffset(10, birthday); }
  GetProfileResponseBuilder(flatbuffers::FlatBufferBuilder &_fbb) : fbb_(_fbb) { start_ = fbb_.StartTable(); }
  GetProfileResponseBuilder &operator=(const GetProfileResponseBuilder &);
  flatbuffers::Offset<GetProfileResponse> Finish() {
    auto o = flatbuffers::Offset<GetProfileResponse>(fbb_.EndTable(start_, 4));
    return o;
  }
};

inline flatbuffers::Offset<GetProfileResponse> CreateGetProfileResponse(flatbuffers::FlatBufferBuilder &_fbb,
   fbs::Status status_code = fbs::Status_OK,
   flatbuffers::Offset<fbs::Session> session = 0,
   flatbuffers::Offset<flatbuffers::String> nickname = 0,
   flatbuffers::Offset<flatbuffers::String> birthday = 0) {
  GetProfileResponseBuilder builder_(_fbb);
  builder_.add_birthday(birthday);
  builder_.add_nickname(nickname);
  builder_.add_session(session);
  builder_.add_status_code(status_code);
  return builder_.Finish();
}

inline const fbs::account::GetProfileResponse *GetGetProfileResponse(const void *buf) { return flatbuffers::GetRoot<fbs::account::GetProfileResponse>(buf); }

inline bool VerifyGetProfileResponseBuffer(flatbuffers::Verifier &verifier) { return verifier.VerifyBuffer<fbs::account::GetProfileResponse>(); }

inline void FinishGetProfileResponseBuffer(flatbuffers::FlatBufferBuilder &fbb, flatbuffers::Offset<fbs::account::GetProfileResponse> root) { fbb.Finish(root); }

}  // namespace account
}  // namespace fbs

#endif  // FLATBUFFERS_GENERATED_GETPROFILERESP_FBS_ACCOUNT_H_
