// automatically generated by the FlatBuffers compiler, do not modify

#ifndef FLATBUFFERS_GENERATED_SEARCHRESP_FBS_ACCOUNT_H_
#define FLATBUFFERS_GENERATED_SEARCHRESP_FBS_ACCOUNT_H_

#include "flatbuffers/flatbuffers.h"

namespace fbs {
struct Session;
struct GeneralResponse;
}  // namespace fbs

namespace fbs {
namespace account {

struct SearchResponse;

struct SearchResponse FLATBUFFERS_FINAL_CLASS : private flatbuffers::Table {
  fbs::Status status_code() const { return static_cast<fbs::Status>(GetField<int8_t>(4, 0)); }
  const fbs::Session *session() const { return GetPointer<const fbs::Session *>(6); }
  const flatbuffers::Vector<flatbuffers::Offset<flatbuffers::String>> *results() const { return GetPointer<const flatbuffers::Vector<flatbuffers::Offset<flatbuffers::String>> *>(8); }
  bool Verify(flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<int8_t>(verifier, 4 /* status_code */) &&
           VerifyField<flatbuffers::uoffset_t>(verifier, 6 /* session */) &&
           verifier.VerifyTable(session()) &&
           VerifyField<flatbuffers::uoffset_t>(verifier, 8 /* results */) &&
           verifier.Verify(results()) &&
           verifier.VerifyVectorOfStrings(results()) &&
           verifier.EndTable();
  }
};

struct SearchResponseBuilder {
  flatbuffers::FlatBufferBuilder &fbb_;
  flatbuffers::uoffset_t start_;
  void add_status_code(fbs::Status status_code) { fbb_.AddElement<int8_t>(4, static_cast<int8_t>(status_code), 0); }
  void add_session(flatbuffers::Offset<fbs::Session> session) { fbb_.AddOffset(6, session); }
  void add_results(flatbuffers::Offset<flatbuffers::Vector<flatbuffers::Offset<flatbuffers::String>>> results) { fbb_.AddOffset(8, results); }
  SearchResponseBuilder(flatbuffers::FlatBufferBuilder &_fbb) : fbb_(_fbb) { start_ = fbb_.StartTable(); }
  SearchResponseBuilder &operator=(const SearchResponseBuilder &);
  flatbuffers::Offset<SearchResponse> Finish() {
    auto o = flatbuffers::Offset<SearchResponse>(fbb_.EndTable(start_, 3));
    return o;
  }
};

inline flatbuffers::Offset<SearchResponse> CreateSearchResponse(flatbuffers::FlatBufferBuilder &_fbb,
   fbs::Status status_code = fbs::Status_OK,
   flatbuffers::Offset<fbs::Session> session = 0,
   flatbuffers::Offset<flatbuffers::Vector<flatbuffers::Offset<flatbuffers::String>>> results = 0) {
  SearchResponseBuilder builder_(_fbb);
  builder_.add_results(results);
  builder_.add_session(session);
  builder_.add_status_code(status_code);
  return builder_.Finish();
}

inline const fbs::account::SearchResponse *GetSearchResponse(const void *buf) { return flatbuffers::GetRoot<fbs::account::SearchResponse>(buf); }

inline bool VerifySearchResponseBuffer(flatbuffers::Verifier &verifier) { return verifier.VerifyBuffer<fbs::account::SearchResponse>(); }

inline void FinishSearchResponseBuffer(flatbuffers::FlatBufferBuilder &fbb, flatbuffers::Offset<fbs::account::SearchResponse> root) { fbb.Finish(root); }

}  // namespace account
}  // namespace fbs

#endif  // FLATBUFFERS_GENERATED_SEARCHRESP_FBS_ACCOUNT_H_
