// automatically generated by the FlatBuffers compiler, do not modify

#ifndef FLATBUFFERS_GENERATED_SEARCHREQ_FBS_ACCOUNT_H_
#define FLATBUFFERS_GENERATED_SEARCHREQ_FBS_ACCOUNT_H_

#include "flatbuffers/flatbuffers.h"

namespace fbs {
struct Session;
struct GeneralResponse;
}  // namespace fbs

namespace fbs {
namespace account {

struct SearchRequest;

struct SearchRequest FLATBUFFERS_FINAL_CLASS : private flatbuffers::Table {
  const fbs::Session *session() const { return GetPointer<const fbs::Session *>(4); }
  const flatbuffers::String *query_str() const { return GetPointer<const flatbuffers::String *>(6); }
  bool Verify(flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<flatbuffers::uoffset_t>(verifier, 4 /* session */) &&
           verifier.VerifyTable(session()) &&
           VerifyField<flatbuffers::uoffset_t>(verifier, 6 /* query_str */) &&
           verifier.Verify(query_str()) &&
           verifier.EndTable();
  }
};

struct SearchRequestBuilder {
  flatbuffers::FlatBufferBuilder &fbb_;
  flatbuffers::uoffset_t start_;
  void add_session(flatbuffers::Offset<fbs::Session> session) { fbb_.AddOffset(4, session); }
  void add_query_str(flatbuffers::Offset<flatbuffers::String> query_str) { fbb_.AddOffset(6, query_str); }
  SearchRequestBuilder(flatbuffers::FlatBufferBuilder &_fbb) : fbb_(_fbb) { start_ = fbb_.StartTable(); }
  SearchRequestBuilder &operator=(const SearchRequestBuilder &);
  flatbuffers::Offset<SearchRequest> Finish() {
    auto o = flatbuffers::Offset<SearchRequest>(fbb_.EndTable(start_, 2));
    return o;
  }
};

inline flatbuffers::Offset<SearchRequest> CreateSearchRequest(flatbuffers::FlatBufferBuilder &_fbb,
   flatbuffers::Offset<fbs::Session> session = 0,
   flatbuffers::Offset<flatbuffers::String> query_str = 0) {
  SearchRequestBuilder builder_(_fbb);
  builder_.add_query_str(query_str);
  builder_.add_session(session);
  return builder_.Finish();
}

inline const fbs::account::SearchRequest *GetSearchRequest(const void *buf) { return flatbuffers::GetRoot<fbs::account::SearchRequest>(buf); }

inline bool VerifySearchRequestBuffer(flatbuffers::Verifier &verifier) { return verifier.VerifyBuffer<fbs::account::SearchRequest>(); }

inline void FinishSearchRequestBuffer(flatbuffers::FlatBufferBuilder &fbb, flatbuffers::Offset<fbs::account::SearchRequest> root) { fbb.Finish(root); }

}  // namespace account
}  // namespace fbs

#endif  // FLATBUFFERS_GENERATED_SEARCHREQ_FBS_ACCOUNT_H_
