// automatically generated by the FlatBuffers compiler, do not modify

#ifndef FLATBUFFERS_GENERATED_VIEWFRIENDREQ_FBS_ACCOUNT_H_
#define FLATBUFFERS_GENERATED_VIEWFRIENDREQ_FBS_ACCOUNT_H_

#include "flatbuffers/flatbuffers.h"

namespace fbs {
struct Session;
struct GeneralResponse;
}  // namespace fbs

namespace fbs {
namespace account {

struct ViewFriendRequest;

struct ViewFriendRequest FLATBUFFERS_FINAL_CLASS : private flatbuffers::Table {
  const fbs::Session *session() const { return GetPointer<const fbs::Session *>(4); }
  bool Verify(flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<flatbuffers::uoffset_t>(verifier, 4 /* session */) &&
           verifier.VerifyTable(session()) &&
           verifier.EndTable();
  }
};

struct ViewFriendRequestBuilder {
  flatbuffers::FlatBufferBuilder &fbb_;
  flatbuffers::uoffset_t start_;
  void add_session(flatbuffers::Offset<fbs::Session> session) { fbb_.AddOffset(4, session); }
  ViewFriendRequestBuilder(flatbuffers::FlatBufferBuilder &_fbb) : fbb_(_fbb) { start_ = fbb_.StartTable(); }
  ViewFriendRequestBuilder &operator=(const ViewFriendRequestBuilder &);
  flatbuffers::Offset<ViewFriendRequest> Finish() {
    auto o = flatbuffers::Offset<ViewFriendRequest>(fbb_.EndTable(start_, 1));
    return o;
  }
};

inline flatbuffers::Offset<ViewFriendRequest> CreateViewFriendRequest(flatbuffers::FlatBufferBuilder &_fbb,
   flatbuffers::Offset<fbs::Session> session = 0) {
  ViewFriendRequestBuilder builder_(_fbb);
  builder_.add_session(session);
  return builder_.Finish();
}

inline const fbs::account::ViewFriendRequest *GetViewFriendRequest(const void *buf) { return flatbuffers::GetRoot<fbs::account::ViewFriendRequest>(buf); }

inline bool VerifyViewFriendRequestBuffer(flatbuffers::Verifier &verifier) { return verifier.VerifyBuffer<fbs::account::ViewFriendRequest>(); }

inline void FinishViewFriendRequestBuffer(flatbuffers::FlatBufferBuilder &fbb, flatbuffers::Offset<fbs::account::ViewFriendRequest> root) { fbb.Finish(root); }

}  // namespace account
}  // namespace fbs

#endif  // FLATBUFFERS_GENERATED_VIEWFRIENDREQ_FBS_ACCOUNT_H_
