#include "core.h"
#include "account/login_generated.h"
#include "account/logout_req_generated.h"
#include "account/logout_resp_generated.h"
#include "account/register_generated.h"
#include "account/remove_req_generated.h"
#include "account/remove_resp_generated.h"
