// automatically generated by the FlatBuffers compiler, do not modify

#ifndef FLATBUFFERS_GENERATED_EDITPOSTPERMREQ_FBS_POST_H_
#define FLATBUFFERS_GENERATED_EDITPOSTPERMREQ_FBS_POST_H_

#include "flatbuffers/flatbuffers.h"

#include "types_generated.h"
#include "post_perm_generated.h"

namespace fbs {
struct Session;
struct GeneralResponse;
}  // namespace fbs
namespace fbs {
namespace post {
struct PostPermission;
}  // namespace post
}  // namespace fbs

namespace fbs {
namespace post {

struct EditPostPermissionRequest;

struct EditPostPermissionRequest FLATBUFFERS_FINAL_CLASS : private flatbuffers::Table {
  const fbs::Session *session() const { return GetPointer<const fbs::Session *>(4); }
  uint64_t post_id() const { return GetField<uint64_t>(6, 0); }
  const fbs::post::PostPermission *permission() const { return GetPointer<const fbs::post::PostPermission *>(8); }
  bool Verify(flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<flatbuffers::uoffset_t>(verifier, 4 /* session */) &&
           verifier.VerifyTable(session()) &&
           VerifyField<uint64_t>(verifier, 6 /* post_id */) &&
           VerifyField<flatbuffers::uoffset_t>(verifier, 8 /* permission */) &&
           verifier.VerifyTable(permission()) &&
           verifier.EndTable();
  }
};

struct EditPostPermissionRequestBuilder {
  flatbuffers::FlatBufferBuilder &fbb_;
  flatbuffers::uoffset_t start_;
  void add_session(flatbuffers::Offset<fbs::Session> session) { fbb_.AddOffset(4, session); }
  void add_post_id(uint64_t post_id) { fbb_.AddElement<uint64_t>(6, post_id, 0); }
  void add_permission(flatbuffers::Offset<fbs::post::PostPermission> permission) { fbb_.AddOffset(8, permission); }
  EditPostPermissionRequestBuilder(flatbuffers::FlatBufferBuilder &_fbb) : fbb_(_fbb) { start_ = fbb_.StartTable(); }
  EditPostPermissionRequestBuilder &operator=(const EditPostPermissionRequestBuilder &);
  flatbuffers::Offset<EditPostPermissionRequest> Finish() {
    auto o = flatbuffers::Offset<EditPostPermissionRequest>(fbb_.EndTable(start_, 3));
    return o;
  }
};

inline flatbuffers::Offset<EditPostPermissionRequest> CreateEditPostPermissionRequest(flatbuffers::FlatBufferBuilder &_fbb,
   flatbuffers::Offset<fbs::Session> session = 0,
   uint64_t post_id = 0,
   flatbuffers::Offset<fbs::post::PostPermission> permission = 0) {
  EditPostPermissionRequestBuilder builder_(_fbb);
  builder_.add_post_id(post_id);
  builder_.add_permission(permission);
  builder_.add_session(session);
  return builder_.Finish();
}

inline const fbs::post::EditPostPermissionRequest *GetEditPostPermissionRequest(const void *buf) { return flatbuffers::GetRoot<fbs::post::EditPostPermissionRequest>(buf); }

inline bool VerifyEditPostPermissionRequestBuffer(flatbuffers::Verifier &verifier) { return verifier.VerifyBuffer<fbs::post::EditPostPermissionRequest>(); }

inline void FinishEditPostPermissionRequestBuffer(flatbuffers::FlatBufferBuilder &fbb, flatbuffers::Offset<fbs::post::EditPostPermissionRequest> root) { fbb.Finish(root); }

}  // namespace post
}  // namespace fbs

#endif  // FLATBUFFERS_GENERATED_EDITPOSTPERMREQ_FBS_POST_H_
